version: "2"

run:
  timeout: 2m

linters-settings:
  revive:
    exclude:
      - test-package
      - package-comments
      - unnecessary-init
      - var-declaration
      - builtin-shadow
      - varnamelen
    rules:
      - name: varnamelen
        arguments: [1]

  wsl_v5:
    allow-first-in-block: true
    allow-whole-block: false
    branch-max-lines: 2

linters:
  default: all
  enable:
    - govet
    - errcheck
    - bodyclose
    - copyloopvar
    - depguard
    - dogsled
    - dupl
    - errorlint
    - gocheckcompilerdirectives
    - goconst
    - gocritic
    - gocyclo
    - godox
    - goprintffuncname
    - gosec
    - intrange
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - staticcheck
    - testifylint
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl_v5

  disable:
    - tagliatelle
    - gochecknoglobals
    - mnd
    - testpackage
    - varnamelen
    - paralleltest
    - gochecknoinits
    - funlen
